# Enable extended keys globally
set -s extended-keys on
set -g allow-passthrough on

# Append features for different terminal emulators
set -as terminal-features 'xterm*:extkeys'
set -as terminal-features 'alacritty:extkeys'
set -as terminal-features 'kitty:extkeys'
set -as terminal-features 'ghostty:extkeys'

